# Generated by Django 5.1.2 on 2024-11-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Category", models.CharField(max_length=100)),
                ("Quantity_Sold", models.IntegerField()),
                ("Prediction", models.FloatField()),
                ("Total_Sales", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Country", models.CharField(max_length=100)),
                ("Place", models.CharField(max_length=100)),
                ("Category", models.CharField(max_length=100)),
                ("Product_ID", models.CharField(max_length=100)),
                ("Price", models.FloatField()),
                ("Discount", models.FloatField()),
                ("Quantity_Sold", models.IntegerField()),
                ("Customer_Rating", models.FloatField()),
                ("Total_Sales", models.FloatField()),
            ],
        ),
    ]
